GET http://localhost:3000





###
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "firstname": "Thembi",
    "lastname": "Grace",
    "email": "missgracemgabi@gmail.com",
    "password": "123456"
}

